### ISSUE TITLE
Spleef layer disappearing on match start

### ISSUE THREAD

**Issue by Zach443** [BattlePlugins/ArenaSpleef#1]
I have gotten multiple reports of the snow layer turning to air when what sounds like the preStart is begun. 

Evidence: 

http://dev.bukkit.org/bukkit-plugins/battlearena2/#c176
http://dev.bukkit.org/bukkit-plugins/arenaspleef/#c1094
http://dev.bukkit.org/bukkit-plugins/arenaspleef/#c1093

Not sure what this is all about, because @Europia79 and I tested this over the weekend and it worked fine. I think we need to test it out again and see if it happens.

**Comment by lasa11** [comment]
If you manually save a schematic with //schematic save, the result schematic's things can be seen inside MCEdit, but with the ones that BattleArena creates, they seem to be empty. And manually doing //schematic load BattleArena schematic and then //paste, it pastes just air. Something seems to be wrong with the schematic saving.

**Comment by xion87** [comment]
maybe can @Paaattiii can help out (owner of woolgame battlearena plugin)

**Comment by Paaattiii** [comment]
The saveSchematic method from WorldEditUtil seems to be wrong. I rewite this and in my case, its works fine. 

https://github.com/Europia79/WorldEditUtil/pull/1

**Comment by Zach443** [comment]
Resolved by above Pull Request.
