### ISSUE TITLE
Spleef superpick

### ISSUE THREAD

**Issue by xion87** [BattlePlugins/ArenaSpleef#2]
superpick: true ## superpick allows instantenous block breaking
superpick_item: 277 ## Gold shovel

As i remember time ago superpick must be not consumed and must be unbreakable... now it consume real fast....

**Comment by Zach443** [comment]
Nothing has been changed in the spleef code for quite some time. The reason for your shovels breaking extremely fast is that they are gold. Gold shovels are like wood, and will thus wear out very quickly in something like spleef. The default tool is a diamond shovel, which would last much longer than any game of spleef. If you need to use a gold shovel you could add Unbreaking 10 or something on it.

**Comment by xion87** [comment]
Is not how it would work, superpick must be able to destroy any BLOCK types (and not only snow and glass), this plugin is pretty without use if you can't fix this small thing...

**Comment by lDucks** [comment]
This seems like a non-issue, closing.

**Comment by Europia79** [comment]
> superpick_item: 277

His 277 is a Diamond Shovel. The default is 284 which is the Gold Shovel. I will have to test this out

**Comment by xion87** [comment]
i dont think it fix that, it lose the durability..

**Comment by Zach443** [comment]
@xion87 I looked through the code and I don't see anything showing that the durability of the super pick has ever been modified.
